<?php 
//init
$auth=Zend_Auth::getInstance();
$ua=new Zend_Http_UserAgent();
$config = Zend_Registry::get('config');
?>
<!DOCTYPE html>
<html>
	<head>
	<meta charset="UTF-8">
	<meta name="DESCRIPTION" content="<?php echo $this->t->_('DESCRIPTION');?>" />
	<meta name="KEYWORDS" content="" />
	<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />
<?php
$mobile=false;
if ($config->mobile) {
	try {
		$device=$ua->getDevice();
		$mobile=$device->getFeature('is_mobile');
	} catch (Zend_Http_UserAgent_Exception $e) {
		$mobile=true;
	}
}
echo $this->headLink()->prependStylesheet($this->baseUrl() . '/common/css/css.php'.($mobile? '?l=m' : ''));
echo $this->headScript()->prependFile($this->baseUrl('/common/js/js.php'));
if ($this->t->getLocale()!='en') echo '<script tipe="text/javascript" src="'.$this->baseURL('/common/js/localization/messages_'.$this->t->getLocale().'.js').'"></script>';
echo '<script tipe="text/javascript">
<!--
var path="'.$this->baseUrl().'";';
if ($this->logger) {
	foreach ($this->logger as $log) {
		echo 'console.log("'.$log['timestamp'].' - '.$log['priorityName'].' - '.($log['info']? $log[info].': ' : '').'",'.$log['message'].');';
	}
}
echo '//-->
</script>';
$this->headTitle()->setSeparator(' - ');
$this->headTitle($config->site);
echo $this->headTitle();
?>
	</head>
	<body>
<?php 
//setcookie('closeadlang','false',time()-604800,'/');$_COOKIE['closeadlang']=true;

if (!in_array($this->t->getLocale(), $this->t->getList()) || (Zend_Registry::get('langnotsup'))&&!$_COOKIE['closeadlang']) {
	//setcookie('closeadlang','false',time()+604800,'/');$_COOKIE['closeadlang']=true;
	?>
	<div class="ui-state-error"><button class="close" onClick="$.cookie('closeadlang','true',{expires:7,path:'/'});$(this).parent().hide();">[CLOSE]</button> [LANGUAGE] <a href="https://github.com/pagliaccio/login">https://github.com/pagliaccio/login</a></div>
	<?php 
}
?>
		<div id="loader" style="display: none;">
			<div></div>
		</div>
		<div id="header">
			<h1><?php echo $config->site;?></h1>
		</div>
		<div id="locale">
			language
			<form action="<?php echo $this->url();?>">
			<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
		<div id="container">
		<?php
		$page=array(
			array('label'=>'Home'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'index'
				,'order'=>0
				,'icon'=>'common/img/menu/index.png'
				//,'iconSize'=>32
				//,'text'=>false //display or not display a text?
			)
			,array('label'=>'Login'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'index'
				,'order'=>1
				,'resource'=>'login'
				,'privilege'=>'index'
			)
			,array('label'=>'Logout'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'logout'
				,'order'=>2
				,'resource'=>'login'
				,'privilege'=>'logout'
			)
			,array('label'=>'[REG]'
				,'module'=>'default'
				,'controller' => 'reg'
				,'action'=>'index'
				,'order'=>3
				,'resource'=>'reg'
				,'privilege'=>'index'
			)
			,array('label'=>'[PROFILE]'
					,'module'=>'default'
					,'controller' => 'profile'
					,'action'=>'index'
					,'order'=>4
					,'resource'=>'profile'
			)
			,array('label'=>'Credits'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'credits'
				,'order'=>100
			)
		);
		/*echo $this->myMenu()->add(array('label'=>'yourpage'
				,'module'=>'default'
				,'controller' => 'yourpage'
				,'action'=>'index'
				,'order'=>0
			))
			->add($label,$module,$controller,$action,$order,$resource,$privilege);*/
		echo $this->myMenu($page);
		echo $this->layout()->content; ?>
	</div>
	<div id="footer">
		footer
	</div>
</body>
</html>
